service: hello-serverless

frameworkVersion: "2"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
  add:
    handler: add.add
    events:
      - http:
          path: math/add
          method: post
          cors: true
